### ISSUE TITLE
zhCN Localization

### ISSUE THREAD

**Issue by Qcat0214** [Road-block/PingoMatic#1]
["Add debuff"] = "添加Debuff",
  ["Add name to Whitelist"] = "添加名字到白名单",
  ["Add"] = "添加",
  ["Alpha"] = "透明度",
  ["Arrow Fade Time"] = "箭头消失时间",
  ["Arrow Options"] = "箭头选项",
  ["Arrow Refresh Rate"] = "箭头刷新率",
  ["Arrow Texture"] = "箭头纹理",
  ["Arrow"] = "箭头",
  ["Assist"] = "协助(有A的人)",
  ["Autoping Options"] = "自动Ping选项",
  ["Autoping"] = "自动Ping",
  ["Color"] = "颜色",
  ["Continuous Ping"] = "连续的Ping",
  ["Coords"] = "坐标",
  ["Debuff"] = "Debuff",
  ["DebuffList Management"] = "Debuff列表管理",
  ["DebuffList"] = "Debuff列表",
  ["Disabling"] = "禁用",
  ["FPS"] = "FPS",
  ["Fade"] = "消失",
  ["Filter"] = "过滤",
  ["GPS Color"] = "GPS颜色",
  ["GPS Flash Color"] = "GPS闪烁颜色",
  ["GPS"] = "GPS",
  ["Health"] = "血量",
  ["Hide minimap icon"] = "隐藏小地图图标",
  ["Invalid Coord Input. Use: x[.xx] y[.yy]"] = "无效的坐标.请输入: x[.xx] y[.yy]",
  ["Leader"] = "队长/团长",
  ["Max rate of autoping"] = "自动Ping的最大速率",
  ["Max repeats of autoping"] = "自动Ping的最大刷新率",
  ["Only show pings from"] = "只显示ping的来源",
  ["Periodic"] = "周期性",
  ["Ping me at Low Health (100 to disable)"] = "在我低血时Ping我(100为禁用)",
  ["Ping me when Debuffed"] = "当我中Debuff时Ping我",
  ["Pinger"] = "Ping者",
  ["PingoMatic"] = "PingoMatic",
  ["Plague"] = "瘟疫",
  ["Point to Custom Coords\nx.xx y.yy"] = "自定义的坐标点\nx.xx y.yy",
  ["Radius"] = "半径",
  ["Rate"] = "速度",
  ["Ratio"] = "比例",
  ["Remove debuff"] = "删除debuff",
  ["Remove name from Whitelist"] = "从白名单中删除名字",
  ["Remove"] = "删除",
  ["Repeat"] = "重复",
  ["Scale"] = "大小",
  ["Session persistent Arrow\nx.xx y.yy\nType |cffC0C0C0%s|r to remove"] = "本次游戏持续的箭头\nx.xx y.yy\n使用 |cffC0C0C0%s|r 为删除",
  ["Set Arrow Alpha"] = "设置箭头透明度",
  ["Set Arrow Color"] = "设置箭头颜色",
  ["Set Arrow Radius"] = "设置箭头半径",
  ["Set Arrow Ratio"] = "设置箭头比例",
  ["Set Arrow Scaling"] = "设置箭头大小",
  ["Set Arrow Width"] = "设置箭头宽度",
  ["Set GPS Arrow Color"] = "设置GPS箭头颜色",
  ["Set GPS Arrow Flash Color"] = "设置GPS箭头闪烁颜色",
  ["Show Who Pinged on Minimap"] = "小地图显示谁的Ping",
  ["Texture"] = "纹理",
  ["Whitelist Management"] = "白名单管理",
  ["Whitelist"] = "白名单",
  ["Width"] = "宽度",
  ["|cffFFA500Click:|r Ping my location\n|cffFFA500Right-Click:|r Options"] = "|cffFFA500点击:|r Ping我的位置\n|cffFFA500右键:|r 选项",

**Comment by Road-block** [comment]
fe8a372
